### ISSUE TITLE
[Bug] TH tries to load Mobly module and fails whenever an error  occurs during SDK Python Test's execution.

### ISSUE THREAD

**Issue by gladystonfranca** [project-chip/certification-tool-backend#66]
### Describe the bug

When an Exception is raised during SDK Python Tests execution, TH  raises a second  error on top of that:
ModuleNotFoundError: No module named 'mobly'

### Steps to reproduce the behavior

Edit: TC_ACE_1_3.py (Or any other Test Script)

Replace TH2 for TH1 on this line:
     `await self.read_descriptor_expect_unsupported_access(TH2)`

Execute the test on TH.

### Expected behavior

Only the error related to the changed value should be raised.

`PYTHON_TEST | 2024-02-06 20:20:13.898 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | [MatterTest] 02-06 20:20:12.693 ERROR Exception occurred in test_TC_ACE_1_3.
PYTHON_TEST | 2024-02-06 20:20:13.899 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | Traceback (most recent call last):
PYTHON_TEST | 2024-02-06 20:20:13.900 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 783, in exec_one_test
PYTHON_TEST | 2024-02-06 20:20:13.901 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     test_method()
PYTHON_TEST | 2024-02-06 20:20:13.902 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 1386, in async_runner
PYTHON_TEST | 2024-02-06 20:20:13.903 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return asyncio.run(runner_with_timeout)
PYTHON_TEST | 2024-02-06 20:20:13.904 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
PYTHON_TEST | 2024-02-06 20:20:13.905 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return loop.run_until_complete(main)
PYTHON_TEST | 2024-02-06 20:20:13.907 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
PYTHON_TEST | 2024-02-06 20:20:13.908 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return future.result()
PYTHON_TEST | 2024-02-06 20:20:13.909 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
PYTHON_TEST | 2024-02-06 20:20:13.910 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return fut.result()
PYTHON_TEST | 2024-02-06 20:20:13.911 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/TC_ACE_1_3.py", line 182, in test_TC_ACE_1_3
PYTHON_TEST | 2024-02-06 20:20:13.912 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     await self.read_descriptor_expect_unsupported_access(TH1)
PYTHON_TEST | 2024-02-06 20:20:13.913 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/TC_ACE_1_3.py", line 46, in read_descriptor_expect_unsupported_access
PYTHON_TEST | 2024-02-06 20:20:13.915 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     await self.read_single_attribute_expect_error(
PYTHON_TEST | 2024-02-06 20:20:13.916 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 804, in read_single_attribute_expect_error
PYTHON_TEST | 2024-02-06 20:20:13.917 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     asserts.assert_true(error_type_ok, err_msg)
PYTHON_TEST | 2024-02-06 20:20:13.918 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 353, in assert_true
PYTHON_TEST | 2024-02-06 20:20:13.919 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     fail(msg, extras)
PYTHON_TEST | 2024-02-06 20:20:13.921 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 475, in fail
PYTHON_TEST | 2024-02-06 20:20:13.922 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     raise signals.TestFailure(msg, extras)
PYTHON_TEST | 2024-02-06 20:20:13.923 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | mobly.signals.TestFailure: Details=Did not see expected error when reading <class 'chip.clusters.Objects.Descriptor'>:<class 'chip.clusters.Objects.Descriptor.Attributes.DeviceTypeList'>, Extras=None`

Current Behavior

An additional error related to not being able to load Mobly module is raised as well:

`PYTHON_TEST | 2024-02-06 17:57:57.217 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | [MatterTest] 02-06 17:57:56.007 ERROR Exception occurred in test_TC_ACE_1_3.
PYTHON_TEST | 2024-02-06 17:57:57.219 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | Traceback (most recent call last):
PYTHON_TEST | 2024-02-06 17:57:57.224 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 783, in exec_one_test
PYTHON_TEST | 2024-02-06 17:57:57.226 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     test_method()
PYTHON_TEST | 2024-02-06 17:57:57.227 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 1386, in async_runner
PYTHON_TEST | 2024-02-06 17:57:57.229 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return asyncio.run(runner_with_timeout)
PYTHON_TEST | 2024-02-06 17:57:57.233 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
PYTHON_TEST | 2024-02-06 17:57:57.235 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return loop.run_until_complete(main)
PYTHON_TEST | 2024-02-06 17:57:57.237 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
PYTHON_TEST | 2024-02-06 17:57:57.238 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return future.result()
PYTHON_TEST | 2024-02-06 17:57:57.243 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
PYTHON_TEST | 2024-02-06 17:57:57.245 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return fut.result()
PYTHON_TEST | 2024-02-06 17:57:57.247 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/TC_ACE_1_3.py", line 182, in test_TC_ACE_1_3
PYTHON_TEST | 2024-02-06 17:57:57.249 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     await self.read_descriptor_expect_unsupported_access(TH1)
PYTHON_TEST | 2024-02-06 17:57:57.252 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/TC_ACE_1_3.py", line 46, in read_descriptor_expect_unsupported_access
PYTHON_TEST | 2024-02-06 17:57:57.254 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     await self.read_single_attribute_expect_error(
PYTHON_TEST | 2024-02-06 17:57:57.257 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 804, in read_single_attribute_expect_error
PYTHON_TEST | 2024-02-06 17:57:57.260 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     asserts.assert_true(error_type_ok, err_msg)
PYTHON_TEST | 2024-02-06 17:57:57.262 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 353, in assert_true
PYTHON_TEST | 2024-02-06 17:57:57.267 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     fail(msg, extras)
PYTHON_TEST | 2024-02-06 17:57:57.269 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/asserts.py", line 475, in fail
PYTHON_TEST | 2024-02-06 17:57:57.271 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     raise signals.TestFailure(msg, extras)
PYTHON_TEST | 2024-02-06 17:57:57.273 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | mobly.signals.TestFailure: Details=Did not see expected error when reading <class 'chip.clusters.Objects.Descriptor'>:<class 'chip.clusters.Objects.Descriptor.Attributes.DeviceTypeList'>, Extras=None
PYTHON_TEST | 2024-02-06 17:57:57.274 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | [MatterTest] 02-06 17:57:56.036 ERROR Exception happened when executing on_fail for test_TC_ACE_1_3.
PYTHON_TEST | 2024-02-06 17:57:57.278 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | Traceback (most recent call last):
PYTHON_TEST | 2024-02-06 17:57:57.280 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 646, in _exec_procedure_func
PYTHON_TEST | 2024-02-06 17:57:57.281 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     func(copy.deepcopy(tr_record))
PYTHON_TEST | 2024-02-06 17:57:57.283 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/local/lib/python3.10/dist-packages/mobly/base_test.py", line 562, in _on_fail
PYTHON_TEST | 2024-02-06 17:57:57.286 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     self.on_fail(record)
PYTHON_TEST | 2024-02-06 17:57:57.288 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/root/python_testing/scripts/sdk/matter_testing_support.py", line 853, in on_fail
PYTHON_TEST | 2024-02-06 17:57:57.290 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     self.runner_hook.test_stop(exception=exception, duration=test_duration)
PYTHON_TEST | 2024-02-06 17:57:57.292 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "<string>", line 2, in test_stop
PYTHON_TEST | 2024-02-06 17:57:57.300 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/multiprocessing/managers.py", line 833, in _callmethod
PYTHON_TEST | 2024-02-06 17:57:57.302 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     raise convert_to_error(kind, result)
PYTHON_TEST | 2024-02-06 17:57:57.304 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | multiprocessing.managers.RemoteError: 
PYTHON_TEST | 2024-02-06 17:57:57.305 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | ---------------------------------------------------------------------------
PYTHON_TEST | 2024-02-06 17:57:57.310 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | Traceback (most recent call last):
PYTHON_TEST | 2024-02-06 17:57:57.312 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/multiprocessing/managers.py", line 253, in serve_client
PYTHON_TEST | 2024-02-06 17:57:57.314 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     request = recv()
PYTHON_TEST | 2024-02-06 17:57:57.315 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |   File "/usr/lib/python3.10/multiprocessing/connection.py", line 251, in recv
PYTHON_TEST | 2024-02-06 17:57:57.318 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 |     return _ForkingPickler.loads(buf.getbuffer())
PYTHON_TEST | 2024-02-06 17:57:57.321 | test_collections.sdk_tests.support.python_testing.models.utils:handle_logs:65 | ModuleNotFoundError: No module named 'mobly'`

**Comment by gladystonfranca** [comment]
This  second error occurs because the initial exception raised  due to the TH2 string being replaced,  is sent from the process  that executes the test on sdk container to the process that initiate the test case  execution on TH.

**Comment by gladystonfranca** [comment]
Fixed on 
https://github.com/project-chip/certification-tool-backend/pull/67
